# Generated by Django 3.0.2 on 2020-01-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'admin',
                'verbose_name_plural': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('learn', models.TextField()),
                ('prereq', models.TextField()),
                ('status', models.CharField(choices=[('f', 'Free'), ('p', 'Paid')], max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Enduser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'enduser',
                'verbose_name_plural': 'endusers',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'instructor',
                'verbose_name_plural': 'instructors',
            },
        ),
        migrations.CreateModel(
            name='PaymentToInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brainery.Course', verbose_name='')),
                ('enduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brainery.Enduser', verbose_name='')),
            ],
            options={
                'verbose_name': 'PaymentToInstructor',
                'verbose_name_plural': 'PaymentToInstructors',
            },
        ),
        migrations.CreateModel(
            name='PaymentByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brainery.Course', verbose_name='')),
                ('enduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brainery.Enduser', verbose_name='')),
            ],
            options={
                'verbose_name': 'PaymentByUser',
                'verbose_name_plural': 'PaymentByUsers',
            },
        ),
        migrations.CreateModel(
            name='EndusersCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainery.Course', verbose_name='')),
                ('enduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainery.Enduser', verbose_name='')),
            ],
            options={
                'verbose_name': 'EndusersCourse',
                'verbose_name_plural': 'EndusersCourses',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='brainery.Instructor'),
        ),
    ]
