# Generated by Django 3.0.2 on 2020-01-21 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brainery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduserscourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainery.Course'),
        ),
        migrations.AlterField(
            model_name='enduserscourse',
            name='enduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainery.Enduser'),
        ),
        migrations.AlterField(
            model_name='paymentbyuser',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brainery.Course'),
        ),
        migrations.AlterField(
            model_name='paymentbyuser',
            name='enduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brainery.Enduser'),
        ),
        migrations.AlterField(
            model_name='paymenttoinstructor',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brainery.Course'),
        ),
        migrations.AlterField(
            model_name='paymenttoinstructor',
            name='enduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brainery.Enduser'),
        ),
    ]
